/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { ContactShadows, OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import { Suspense } from 'react'

export function Dav(props) {
	const { nodes, materials } = useGLTF("/gltf/Troquel1p0391.gltf");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mesh_0.geometry}
				material={materials.BACK}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mesh_0_1.geometry}
				material={materials.EDGE}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mesh_0_2.geometry}
				material={materials.FRONT}
			/>
		</group>
	);
}

useGLTF.preload("/gltf/Troquel1p0391.gltf");


const Troquel1g0011 = ({ }) => {
	return (

		<Canvas
			style={{}}
			camera={{
				view: {
					enabled: true,
					fullWidth: 100,
					fullHeight: 100,
					offsetX: 0,
					offsetY: -30,
					width: 100,
					height: 100
				},
				focus: 10,
				fov: 80,
				zoom: 3,
				position: [0, 0.5, 1.5]
			}} >
			<ambientLight intensity={2} />
			{/* <pointLight position={[10, 10, 2]} /> */}
			<Suspense fallback={null}>

				<Dav />

			</Suspense>
			<OrbitControls autoRotate autoRotateSpeed={1} />
			<ContactShadows resolution={512} scale={1} position={[0, -0.03, 0]} blur={2} opacity={0.6} far={1} color='#202020' />
		</Canvas>
	)
}
export default Troquel1g0011
